### ISSUE TITLE
Page not reloading after EventSource closed.

### ISSUE THREAD

**Issue by ob6160** [RoboPython/flaskStarter#12]
After EventSource connection is terminated server doesn't serve any further pages.

**Comment by Hoolean** [comment]
Note: this will likely become an issue again when we begin to test asynchronous usage, as Flask is not capable of serving the SSEs and other pages concurrently. Issue #11 should provide a fix for this.

**Comment by RoboPython** [comment]
Fixed. For loop broken out of in the app.py
