### ISSUE TITLE
Improve UI based on user's needs

### ISSUE THREAD

**Issue by RoboPython** [RoboPython/flaskStarter#7]

**Comment by Hoolean** [comment]
Apparently you cannot assign multiple people to an issue. :disappointed:

I will attempt to help design the layout and @ob6160 will help to implement.

**Comment by Hoolean** [comment]
The current UI is adequate for its purpose, as it is bound closely to the command-line usage that previous users will be familiar with. Newer users should still find it intuitive enough to be very usable.
